version: '1.0.0'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_USER: user
      POSTGRES_DB: vacation_project
    ports:
      - "5432:5432"